### ISSUE TITLE
Found Devices: none

### ISSUE THREAD

**Issue by jayeshnaik** [mclarkk/lifxlan#53] opened 2017-06-17 18:10 UTC
I am testing on Windows and not finding devices. verbose_lan shows packets found device none

**Comment by mclarkk** [comment] 2017-06-18 06:37
Do you see them on your phone app?

**Comment by jayeshnaik** [comment] 2017-06-18 11:59
Yes phone so showed items. 2 lamps

**Comment by jayeshnaik** [comment] 2017-06-18 12:00
I have lifx color 1000 lamps

**Comment by mclarkk** [comment] 2017-06-19 02:43
Do you have some kind of VPN setup? If not, is it possible that your network is blocking UDP on certain ports?

**Comment by aptitude** [comment] 2017-07-16 16:49
I can confirm this issue on windows.

Windows with default settings probably interferes with the UDP traffic.

lifxlan works for me on the same computer with Linux as OS, but not with windows 10 or a Linux in a Virtual Machine hosted by Windows 10.

**Comment by mclarkk** [comment] 2017-07-16 22:37
Figured it out! Windows doesn't handle the broadcast address "255.255.255.255" the same way as macOS and Linux. I was able to replicate the problem with a Windows 10 VM. No devices found using `hello_world.py`, even with the firewall completely off. After I replaced the global broadcast address with a broadcast address tailored to my local network address ("162.168.1.255"), it worked fine. I'm working on a more general solution now, and will hopefully get it working soon for those Windows users out there.

**Comment by mclarkk** [comment] 2017-07-16 23:21
I just pushed a fix to the repo and to PyPI, so do whatever you need to do to install the newest version! Windows users should be good to go now.

Note: It will only work with a virtual machine if the VM is in bridge mode.

**Closed by mclarkk** 2017-07-16 23:21 UTC

**Comment by jayeshnaik** [comment] 2017-07-17 00:58
Thanks
