### ISSUE TITLE
device.supports_multizone() or get_multizone_lights()

### ISSUE THREAD

**Issue by Einstein42** [mclarkk/lifxlan#42] opened 2017-02-13 23:40 UTC
lifx:   File "/home/pi/dev/lifx-nodeserver/lifxlan/device.py", line 338, in supports_multizone
lifx:     return self.product_features['multizone']
lifx: TypeError: 'NoneType' object has no attribute '__getitem__'

I have 1 group and 2 lights. Tried just get_lights() and get_multizone_lights(). Both fail same error, same line.

**Comment by mclarkk** [comment] 2017-02-14 21:59
Relevant code starts at line 334 in device.py:

```
def supports_multizone(self):
        if self.product_features == None:
            self.product_features = self.get_product_features()
        return self.product_features['multizone']
```

The issue is that this code assumes that `self.get_product_features()` will succeed, which of course it may not. Obviously the code should be updated to handle the case where the call fails, but in the meantime, it looks like there is a communication issue with at least one of your lights. It must be responding to discovery messages, but not to the `get_product_features()` call. Are all your lights powered on? (Not necessarily with the light shining, but attached to wall power/with the light switch on?) If so, can you share the output of the `hello_world.py` script in the `examples` folder?

**Comment by Einstein42** [comment] 2017-02-14 22:25
`Discovery will go much faster if you provide the number of lights on your LAN:
  python ./helloworld.py <number of lights on LAN>

Discovering lights...

Found 2 light(s):

Lamp
  MAC Address: d0:73:d5:13:27:cc
  IP Address: 10.0.0.218
  Port: 56700
  Service: UDP
  Power: Off
  Location: Office
  Group: James' Office
  Color (HSBK): (22149, 0, 65535, 3500)
  Host Firmware Build Timestamp: 1479957302000000000 (2016-11-24 03:15:02 UTC)
  Host Firmware Build Version: 1.2
  Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
  Wifi Firmware Build Version: 101.62
  Vendor: 1
  Product: 22 (Color 1000)
  Version: 0
  Features: {'color': True, 'multizone': False, 'infrared': False}
  Current Time: 1487111060022489000 (2017-02-14 22:24:20 UTC)
  Uptime (ns): 702002062000000 (195.0 hours)
  Last Downtime Duration +/-5s (ns): 0 (0.0 hours)
  Wifi Signal Strength (mW): 3.98106976718e-07
  Wifi TX (bytes): 212541059
  Wifi RX (bytes): 2065504638

Z
  MAC Address: d0:73:d5:14:9b:32
  IP Address: 10.0.0.184
  Port: 56700
  Service: UDP
  Power: Off
  Location: Office
  Group: James' Office
  Color (HSBK): (1092, 65535, 38010, 3500)
  Host Firmware Build Timestamp: 1479957302000000000 (2016-11-24 03:15:02 UTC)
  Host Firmware Build Version: 1.2
  Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
  Wifi Firmware Build Version: 101.62
  Vendor: 1
  Product: 31 (LIFX Z)
  Version: 0
  Features: {'color': True, 'multizone': True, 'infrared': False}
  Current Time: 1487111061546340000 (2017-02-14 22:24:21 UTC)
  Uptime (ns): 1347884000000 (0.37 hours)
  Last Downtime Duration +/-5s (ns): 0 (0.0 hours)
  Wifi Signal Strength (mW): 9.99999997475e-07
  Wifi TX (bytes): 382927
  Wifi RX (bytes): 4134137`

**Comment by mclarkk** [comment] 2017-02-15 01:14
Well, it seems to be working there. Does the original script you were running still fail?

**Comment by mclarkk** [comment] 2017-02-15 17:53
@Einstein42 I'm keeping this open because even if your script happens to be running successfully now, the code still does not handle failed attempts to fetch attributes in cases where there is a problem talking to the lights. I'll close this issue after submitting a fix.

**Comment by Einstein42** [comment] 2017-02-16 03:50
On another note, I remember changing your WorkflowException exception because it wasn't working in my framework. Seems you changed that back, and I'm getting random lockups again. No matter how hard I try importing your custom WorkflowException from lifxlan.device just WILL NOT catch. Annoying as ALL get out. Any idea's on what I'm doing wrong?

**Comment by mclarkk** [comment] 2017-02-16 05:45
Can you post the code that was giving you issues?

**Comment by Einstein42** [comment] 2017-02-16 14:01
[https://github.com/mclarkk/lifxlan/issues/15](https://github.com/mclarkk/lifxlan/issues/15)

**Comment by mclarkk** [comment] 2017-02-16 23:16
Yeah, this is pretty weird. The WorkflowException is definitely being caught and the message printed out by some part of the lifxlan module before it hits your code. However, I'm trying to figure out which part of the lifxlan library could possibly be catching and printing out this error. I found the part of the module that ought to be catching it, but it shouldn't be printing it out...I'll keep looking.

**Comment by Einstein42** [comment] 2017-02-16 23:17
Thanks for your time!

**Comment by mclarkk** [comment] 2017-02-16 23:27
The issue is in light.py:

```
def get_power(self):
        try:
            response = self.req_with_resp(LightGetPower, LightStatePower)
            self.power_level = response.power_level
        except WorkflowException as e:
            print(e)
        return self.power_level
```

I changed `print(e)` to `pass` and that stopped the message from printing, surprise surprise. Of course, the better design would be to raise all the way up through the module to the user's code, because the user's application logic may different if the light goes offline.

There are actually a lot of places where the lifxlan code either silently catches an error or prints out the error message, which I agree is really obnoxious as a user. I'll go through the code base and turn all those into re-raises. Then your code would be able to catch and handle the WorkflowException.

Thanks for pointing this out, in retrospect those were some pretty silly design decisions on my part. I'll go through and make sure everywhere in the module where something gets printed out, it is only when the verbose flag has been intentionally set by the user.

**Comment by Einstein42** [comment] 2017-03-03 16:21
Awesome, I'm going to try this now and I'll update you. Thanks!

**Comment by mclarkk** [comment] 2017-03-09 02:34
Changed `device.py` so that now it raises an error instead of passing whenever it has trouble talking to the lights while fetching attributes. Also, as mentioned in #15, all exceptions get raised up to the user now so you can decide what to do about the failure (and also suppress messages to STDOUT if needed).

**Closed by mclarkk** 2017-03-09 02:34 UTC
